/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author Anushka Lakshan
 */
public class About extends javax.swing.JDialog {

    /**
     * Creates new form About
     */
    
    private static final Random random = new Random();
    int xVelocity = 2;
    int yVelocity = 1;
    
    int boxWidth = 600;
    int boxHeight = 400;
    
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(boxWidth, boxHeight);
        this.setPreferredSize(new Dimension(boxWidth, boxHeight));
        back.setSize(boxWidth, boxHeight);
        back.setPreferredSize(new Dimension(boxWidth, boxHeight));
        Animated.setLayout(null); // Disable layout manager
        
        
        boxWidth = back.getWidth();
        boxHeight = back.getHeight();
        
        Timer work = new Timer(12,(e) -> {
            animate();
        });
        
        work.start();
        
        
    }

    private void animate(){
        if(Animated.getX() >= boxWidth-Animated.getWidth() || Animated.getX()<0){
            xVelocity = xVelocity * -1;
            changeBGC();
        }
        
        if(Animated.getY() >= boxHeight-(Animated.getHeight()+37) || Animated.getY()<0){
            yVelocity = yVelocity * -1;
            changeBGC();
        }
        
        int newX = Animated.getX() + xVelocity;
        int newY = Animated.getY() + yVelocity;
//        int newY = 10;


        Animated.setLocation(newX, newY);
        
        back.repaint();
        Animated.repaint();
    }
    
    private void changeBGC(){
//        int red = random.nextInt(128);
//        int green = random.nextInt(128);
//        int blue = random.nextInt(128);
          float hue = (float) Math.random(); // Random hue value between 0.0 and 1.0
        float saturation = 1.0f; // Maximum saturation
        float brightness = (float) (Math.random() * 0.4); // Random brightness value between 0.0 and 0.5
        
//        return Color.getHSBColor(hue, saturation, brightness);
        
        back.setBackground(Color.getHSBColor(hue, saturation, brightness));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        Animated = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setAlwaysOnTop(true);
        setName("About"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Animated.setOpaque(false);
        Animated.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Developed & Designed by");
        Animated.add(jLabel1);
        jLabel1.setBounds(6, 6, 176, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Anushka");
        Animated.add(jLabel2);
        jLabel2.setBounds(6, 32, 180, 43);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Lakshan");
        Animated.add(jLabel3);
        jLabel3.setBounds(6, 81, 171, 44);

        back.add(Animated, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 46, 190, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                About dialog = new About(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Animated;
    private javax.swing.JPanel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
