/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Logic.Cashier;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Logic.Conn;
import Logic.HandleEncryption;
import Logic.Manager;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Anushka Lakshan
 */
public class Login extends javax.swing.JFrame {

    Connection conn;
    Statement st;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        Conn DBcon = new Conn();
        this.conn = DBcon.getConn();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Uname = new javax.swing.JTextField();
        Upass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        LoginBTN = new Vendor_Codes.ButtonGradient();
        CoverPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("City Bookshop Login");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("City Bookshop");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 248, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Inventory Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("User Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));
        jPanel1.add(Uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 250, 34));
        jPanel1.add(Upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 250, 34));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/close (2).png"))); // NOI18N
        jLabel5.setToolTipText("Exit");
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 19, 15));
        jLabel5.getAccessibleContext().setAccessibleName("");

        LoginBTN.setText("Login");
        LoginBTN.setColor1(new java.awt.Color(0, 0, 204));
        LoginBTN.setColor2(new java.awt.Color(255, 51, 0));
        LoginBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 250, -1));

        CoverPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/CityBookshop.jpg"))); // NOI18N
        CoverPicture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CoverPictureMouseDragged(evt);
            }
        });
        CoverPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CoverPictureMousePressed(evt);
            }
        });
        jPanel1.add(CoverPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private Point initialClick;
    
    private void CoverPictureMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoverPictureMouseDragged
       int thisX = getLocation().x;
                int thisY = getLocation().y;

                int xMoved = evt.getX() - initialClick.x;
                int yMoved = evt.getY() - initialClick.y;

                int X = thisX + xMoved;
                int Y = thisY + yMoved;

                setLocation(X, Y);
    }//GEN-LAST:event_CoverPictureMouseDragged

    private void CoverPictureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoverPictureMousePressed
        // TODO add your handling code here:
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_CoverPictureMousePressed

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed
        // TODO add your handling code here:
        String uname = Uname.getText();
        String pass = new String(Upass.getPassword());
        
        HandleEncryption handleEncryption = new HandleEncryption();
        String encryptedPassword = handleEncryption.getEncryptedPass(pass);

        String sql = "SELECT * FROM User WHERE Name='"+ uname +"' AND Password='"+ encryptedPassword +"'";
        
        String Lname = null;
        boolean isAdmin = false;
        int userID = 0;
        
        try {
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            

            int rowCount = 0;

            while (rs.next()) {
                rowCount++;
                Lname = rs.getString("Name");
                isAdmin = rs.getBoolean("IsAdmin");
                userID = rs.getInt("ID");
            }

            if (rowCount == 0){
                JOptionPane.showMessageDialog(this, "Logging Failed! Try again..");
            }else{
                
                if(isAdmin){
                    Manager admin = new Manager(Lname,String.valueOf(userID), handleEncryption.getDecryptedPass(encryptedPassword));
                    Dashboard Dash = new Dashboard(admin);
                    Dash.setVisible(true);
                    conn.close();
                    st.close();
                    this.dispose();
                    
                }else{
                    Cashier cash = new Cashier(Lname,String.valueOf(userID), pass);
                    Dashboard Dash = new Dashboard(cash);
                    Dash.setVisible(true);
                    conn.close();
                    st.close();
                    this.dispose();
                }
                
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error : " + e.getMessage());

        }
    }//GEN-LAST:event_LoginBTNActionPerformed

    
     
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoverPicture;
    private Vendor_Codes.ButtonGradient LoginBTN;
    private javax.swing.JTextField Uname;
    private javax.swing.JPasswordField Upass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
